# Setup
title:            DATA PLAYBOOK
tagline:          'California Health and Human Services Agency'
description:      'CHHS Data Playbook'
url:              'http://localhost:4000/dataplaybook-beta'
baseurl:          ''

# markdown:         CommonMarkGhPages

author:
  name:           'California Health and Human Services Agency'
  url:            https://twitter.com/chhsagency

# Custom vars
version:          4.0.1 | May 2020

github:
  repo:           https://github.com/chhsdata/dataplaybook-beta

# Google Analytics
google_analytics: UA-56144207-2

plugins:
  - jemoji